Repository googleapis/nodejs-text-to-speech, pull requests merged in 2018-07, with the labels that each got.

#46 Fixed the wrong region tag
  samples/quickstart.js
Labels: in progress

#29 codegen: v1 GA release
  .mailmap
  CONTRIBUTORS
  package.json
  protos/google/cloud/texttospeech/v1/cloud_tts.proto
  src/index.js
  src/v1/doc/google/cloud/texttospeech/v1/doc_cloud_tts.js
  src/v1/index.js
  src/v1/text_to_speech_client.js
  src/v1/text_to_speech_client_config.json
  synth.py
  test/gapic-v1.js
Labels: type: feature request

#61 chore: require node 8 for samples
  samples/package.json
Labels: cla: yes

#60 chore: move mocha options to mocha.opts
  package.json
  test/mocha.opts
Labels: cla: yes
