Repository googleapis/nodejs-text-to-speech, pull requests merged in 2019-05, with the labels that each got.

#213 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#214 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#215 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#219 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#220 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#221 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#217 build: switches to piping coverage to codecov from Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#222 fix: DEADLINE_EXCEEDED no longer treated as idempotent and retried
  src/v1/text_to_speech_client_config.json
  src/v1beta1/text_to_speech_client_config.json
  synth.metadata
Labels: cla: yes

#224 fix: DEADLINE_EXCEEDED is idempotent
  src/v1/text_to_speech_client_config.json
  src/v1beta1/text_to_speech_client_config.json
  synth.metadata
Labels: cla: yes

#225 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#226 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#227 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/text_to_speech_client.js
  src/v1beta1/text_to_speech_client.js
  synth.metadata
Labels: cla: yes

#228 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#229 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#230 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#232 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#231 build: use repo metadata to generate readme
  .cloud-repo-tools.json
  .gitignore
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  synth.metadata
Labels: cla: yes
