Repository googleapis/nodejs-text-to-speech, pull requests merged in 2020-07, with the labels that each got.

#417 chore(deps): no canvas
  samples/package.json
Labels: cla: yes

#418 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#419 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#422 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#426 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#428 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#429 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#430 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#431 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:run

#432 feat: support MULAW and MP3_64_KBPS audio encoding and support timepointing via SSML <mark> tag
  protos/google/cloud/texttospeech/v1beta1/cloud_tts.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1beta1/text_to_speech_client.ts
  src/v1beta1/text_to_speech_client_config.json
  synth.metadata
Labels: cla: yes, context: full

#434 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
