Repository googleapis/nodejs-text-to-speech, pull requests merged in 2020-11, with the labels that each got.

#461 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full

#463 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/text_to_speech_client.ts
  src/v1beta1/text_to_speech_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: texttospeech, automerge, cla: yes

#466 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/text_to_speech_client.ts
  src/v1beta1/text_to_speech_client.ts
  synth.metadata
Labels: api: texttospeech, cla: yes, context: none

#468 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: texttospeech, automerge, cla: yes, context: full
